name: CI/CD library release

on:
  create:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: clear install
        run: npm ci
      - name: build
        run: npm run build
      - name: login npm
        run: npm run login -u ${{ secrets.NPM_NAME }} -p ${{ secrets.NPM_PASSWORD }}
      - name: publish
        run: npm publish
